version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "dev-capsule-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bmpga5thxtj4"
s3_prefix = "dev-capsule-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "prod-capsule-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bmpga5thxtj4"
s3_prefix = "prod-capsule-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\" Environment=\"prod\""
image_repositories = []
